// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OrnekWebApi.Models;

#nullable disable

namespace OrnekWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250603070420_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrnekWebApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Price = 100000m,
                            ProductName = "Macbook Pro"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Price = 85000m,
                            ProductName = "Macbook Air"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Price = 90000m,
                            ProductName = "HP Computer"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Price = 80000m,
                            ProductName = "MSI"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
